base:
  host: archipelago.gg
  base_path: /path/to/saves/

games:

# Example
# - host: archipelago.gg
#   port: 34567
#   name: Player1
#   password: roompassword
#   handler: ladx
#   base_path: /path/to/saves/
#   save_file: /gameboy/save.srm

# Anything left unfilled will default to what is in the 'base' entry