# The base dict is merged with your game definitions, set anything common here.
# If set on the game, it will override what is in base.
base:
  host: archipelago.gg
  base_path: /path/to/your/saves/

games:
  # An example game
  - label: my example game

    # Connection info
    port: 12345
    name: Player1
    password: secret

    # The handler is what actually processes the save file
    handler: ladx

    # base_path and save_file are joined to find your save file
    save_file: path/from/base_path/to/savefile.srm
