name: Build ARM 32

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Build package
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/batonogov/pyinstaller-linux:latest
          options: |
            --platform linux/arm/v7
            --volume ${ github.workspace }}/:/src
          run: |
            pip install -r /src/requirements.txt
            pyinstaller --onefile /src/main.py

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/main
